version: "3.7"

services:
  vscode:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      # Docker volume to contain node_modules for performance reason
      - node_modules:/workdir/node_modules
      - ../:/workdir
    entrypoint: sleep infinity
    ports:
      - 3000:3000

volumes:
  node_modules:
